### PR TITLE
THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

### PR DESCRIPTION
**Pull request by Vertex-Client**
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

### CODE REVIEW

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!
- [x] THIS MOD USES CODE FROM OTHERS! WE RECOMMEND YOU NOT TO USE IT!

**Comment by Vertex-Client** [comment]
Closed #1
Closed #2
Opened #1
Opened #2

**Comment by Vertex-Client** [comment]
If you don't remove our code, this will have some consequences for you.

**Comment by Vertex-Client** [comment]
👍 Good boy xD

Let's get Harambe out.....

lol

**Comment by Vertex-Client** [comment]
#1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3 #1 #2 #3

**Comment by ghost** [comment]
seems legit

**Pull request closed without merging**
